version: "3.8"

volumes:
  db-data: {}

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file: .env

  db:
    build: compose/postgres/
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
    volumes:
      - db-data:/var/lib/postgresql
    env_file: .env
    ports:
      - "5433:5432"

