version: "3.8"

volumes:
  db-data: {}

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app/
    depends_on:
      - db
    env_file: .env

  db:
    build: compose/postgres/
    environment:
      POSTGRES_URL: "$POSTGRES_URL"
    volumes:
      - db-data:/var/lib/postgresql
    env_file: .env

